"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
require('./WebSearchTab.module.css');
var styles = {
    filePicker: 'filePicker_0058eef1',
    tabsContainer: 'tabsContainer_0058eef1',
    tabContainer: 'tabContainer_0058eef1',
    nav: 'nav_0058eef1',
    tabHeaderContainer: 'tabHeaderContainer_0058eef1',
    breadcrumbNav: 'breadcrumbNav_0058eef1',
    breadcrumbNavItem: 'breadcrumbNavItem_0058eef1',
    tab: 'tab_0058eef1',
    tabFiles: 'tabFiles_0058eef1',
    scrollablePaneWrapper: 'scrollablePaneWrapper_0058eef1',
    actionButtonsContainer: 'actionButtonsContainer_0058eef1',
    actionButtons: 'actionButtons_0058eef1',
    actionButton: 'actionButton_0058eef1',
    tabHeader: 'tabHeader_0058eef1',
    selectedTab: 'selectedTab_0058eef1',
    header: 'header_0058eef1',
    xlg: 'xlg_0058eef1',
    xxlg: 'xxlg_0058eef1',
    xxxlg: 'xxxlg_0058eef1',
    xxxxlg: 'xxxxlg_0058eef1',
    itemPickerTopBar: 'itemPickerTopBar_0058eef1',
    commandBarNoChevron: 'commandBarNoChevron_0058eef1',
    fileItem: 'fileItem_0058eef1',
    folderItem: 'folderItem_0058eef1',
    fileTypeIcon: 'fileTypeIcon_0058eef1',
    fileTypeIconIcon: 'fileTypeIconIcon_0058eef1',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_0058eef1',
    iconColumnHeader: 'iconColumnHeader_0058eef1',
    fileRow: 'fileRow_0058eef1',
    folderRow: 'folderRow_0058eef1',
    emptyFolder: 'emptyFolder_0058eef1',
    emptyFolderImage: 'emptyFolderImage_0058eef1',
    emptyFolderImageTag: 'emptyFolderImageTag_0058eef1',
    emptyFolderTitle: 'emptyFolderTitle_0058eef1',
    emptyFolderSubText: 'emptyFolderSubText_0058eef1',
    emptyFolderMobile: 'emptyFolderMobile_0058eef1',
    emptyFolderPc: 'emptyFolderPc_0058eef1',
    emptyFolderIcon: 'emptyFolderIcon_0058eef1',
    searchBoxContainer: 'searchBoxContainer_0058eef1',
    searchBoxMedium: 'searchBoxMedium_0058eef1',
    searchBox: 'searchBox_0058eef1',
    dropdownContainer: 'dropdownContainer_0058eef1',
    filterDropdown: 'filterDropdown_0058eef1',
    filePickerFolderCardGrid: 'filePickerFolderCardGrid_0058eef1',
    filePickerFolderCardTile: 'filePickerFolderCardTile_0058eef1',
    filePickerFolderCardPadder: 'filePickerFolderCardPadder_0058eef1',
    filePickerFolderCardSizer: 'filePickerFolderCardSizer_0058eef1',
    filePickerFolderCardImage: 'filePickerFolderCardImage_0058eef1',
    filePickerFolderCardLabel: 'filePickerFolderCardLabel_0058eef1',
    bingGridListCell: 'bingGridListCell_0058eef1',
    bingTile: 'bingTile_0058eef1',
    bingTileContent: 'bingTileContent_0058eef1',
    bingTileFrame: 'bingTileFrame_0058eef1',
    bingTileCheckCircle: 'bingTileCheckCircle_0058eef1',
    bingTileNamePlate: 'bingTileNamePlate_0058eef1',
    isSelected: 'isSelected_0058eef1',
    copyrightLabel: 'copyrightLabel_0058eef1',
    noResultLabel: 'noResultLabel_0058eef1',
    bingTileThumbnail: 'bingTileThumbnail_0058eef1',
    bingGrildList: 'bingGrildList_0058eef1',
};
exports.default = styles;
/* tslint:enable */ 

//# sourceMappingURL=WebSearchTab.module.scss.js.map
